spring.datasource.url=jdbc:postgresql://localhost:5432/ingestion
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

minio.url=http://localhost:9000
minio.access-key=${MINIO_ROOT_USER}
minio.secret-key=${MINIO_ROOT_PASSWORD}
minio.bucket=raw-docs